apiVersion: v1
kind: Secret
metadata:
  name: media-processor-env
type: Opaque
stringData:
  DATABASE_URL: postgresql://media:passwordTest@postgres-service.postgres.svc.cluster.local:5432/media_processor?schema=public
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  WEBHOOK_HMAC_SECRET: change-me-in-prod
