apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: n8n-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/n8n
    type: DirectoryOrCreate