apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      lipton:
        displayname: "Lipton"
        password: "$argon2id$v=19$m=65536,t=3,p=4$/Ui9th1yzzUNbLDc45DpvA$Ge4F8YD7GB5aEXru1dZLxI8pG1RxsHq66/jgzzZrhKY"
        email: "lipton@lipcloud.org"
        groups:
          - admins
