apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--entrypoints.web.forwardedheaders.trustedips=10.42.0.0/16,10.43.0.0/16"
      - "--entrypoints.websecure.forwardedheaders.trustedips=10.42.0.0/16,10.43.0.0/16"
    ports:
      traefik:
        expose:
          default: false
      web:
        redirectTo:
          port: websecure
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
