apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
    ports:
      traefik:
        expose:
          default: false
      web:
        redirectTo:
          port: websecure
        forwardedHeaders:
          trustedIPs:
            - "10.42.0.0/16"
            - "10.43.0.0/16"
      websecure:
        forwardedHeaders:
          trustedIPs:
            - "10.42.0.0/16"
            - "10.43.0.0/16"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
