apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: docker-registry-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/docker-registry
    type: DirectoryOrCreate
