apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: docker-registry-pv
  storageClassName: docker-registry-storage
  resources:
    requests:
      storage: 10Gi
