apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: registry=registry:2
    argocd-image-updater.argoproj.io/registry.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/honeybears/argocd-app-of-apps.git
    targetRevision: HEAD
    path: docker-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
