apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: media-processor=registry.lipcloud.org/media-processor:latest
    argocd-image-updater.argoproj.io/media-processor.update-strategy: digest
  name: media-processor
  namespace: argocd
spec:
  destination:
    namespace: media-processor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: media-processor
    repoURL: https://github.com/honeybears/argocd-app-of-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
