apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "*"
    helm:
      valuesObject:
        logs:
          general:
            level: DEBUG
        api:
          dashboard: true
        ingressRoute:
          dashboard:
            enabled: false
        ports:
          traefik:
            expose:
              default: false
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
            forwardedHeaders:
              trustedIPs:
                - "10.42.0.0/16"
                - "10.43.0.0/16"
          websecure:
            forwardedHeaders:
              trustedIPs:
                - "10.42.0.0/16"
                - "10.43.0.0/16"
        providers:
          kubernetesCRD:
            allowCrossNamespace: true
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
