apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "*"
    helm:
      valuesObject:
        logs:
          general:
            level: DEBUG
        api:
          dashboard: true
        ingressRoute:
          dashboard:
            enabled: false
        additionalArguments:
          - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
          - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
          - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
          - "--entrypoints.web.forwardedheaders.trustedips=10.42.0.0/16,10.43.0.0/16"
          - "--entrypoints.websecure.forwardedheaders.trustedips=10.42.0.0/16,10.43.0.0/16"
        ports:
          traefik:
            expose:
              default: false
        providers:
          kubernetesCRD:
            allowCrossNamespace: true
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
