apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v1.1.1/config/install.yaml
  - imageupdater-cr.yml
patches:
  - target:
      kind: ConfigMap
      name: argocd-image-updater-config
    patch: |-
      - op: add
        path: /data
        value:
          log.level: info
          registries.conf: |
            registries:
              - name: Lipcloud
                api_url: http://registry.lipcloud.org
                prefix: registry.lipcloud.org
                ping: yes
                insecure: yes
                default: false
