---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBcdK923A7roOjBUQmub8gZs4et/bBB++h1ArH6dLTrGloSPqCsK226DeUrpJ54+fO2mxphKK4gAgHVv1BYmGoDMk9f6TIT2z9363TW0331ho0WkHhZTfQcc/3lwrE2coNW6RCOAsY8CSLywUly6rHTv57sY2vtGKtimx3zS20CbKgsgxEtkxqmH/mSftBBJx9cqZ8+SuE1llV0+7Se0el+ERVWR+D6BpZf6pygiVvNBhgwUu1O1BgYg+bm+win/5VGZwjs3BKw/aWkg1TLb5b8njFcK2u8sbRf1rlJne0B1eRR5injLyYf9epjmAvwgAvG3LN9f8Mi1ExPX9LYHWg1VOqT51ogEaqPy8CvvAgr4GpoLJ3Uj4QvTSKvsaA1tcSqlOzJLrjU7VTcyA87O9kGmzDBAb0jxXmtjY7m2I4PECn9Wcv+Rlv5bbtGL+jG0bWDfDdl01q5UAQdjpvVNiJNNnyalE4ePB5nB1SpzG0pMlkk53STCL0KF/Pg+mup70fygGiiPkiPwGsnVL0/Ob0EFgVbiXAWfrAVGtDe+YlQZMpwiBWVSpYdAlUQJ/8wGWKfTZLv9fevV+5FYEQ7m1IOvsSqtGIGatGNgSgrnwjcItptghuibjCSRBFRuPk7Al1F/9QlxCmcXy5/ElkkRdpdPMpF6rXnx3mohVsAU4sQtG/fzt+S5KnzYeQIro7wZRORwd13sluqyDA3
    MINIO_ROOT_USER: AgC9Vh/OBepB7V3LkrKoTnF/iDVPZ2KppS5r0gLFtQqKagUM8trt/6WfYRM3HLM51beuXSw4TmPprflAnRL5USL45hwBH1AxRyLkAwW77zuqhKT81TeNCBrK5fCrcBFRyjLOPNrYZIy4KWreQEojFKE2uuyepWWEexCYOf/UQq6UN/p1ySahdQ+bfhz8tLrVtDl3VL2mK4OtncB6I0xUdver8v5DeeUsalECvJ8yuERdiVmpjXHJwHjw88SOal92h30O0yM1gTvqoG8IW2KG3Vi+ok6l/rp6/JadE6a6U+6H078P4nDcj47YrENortS3X49hNGoJWRzi1LMwyJPmL7jS5te87BgTpzgxMcMWT+eDGZAnCoOwQR5QhMfspnjvb03IStEJQI7cGNsau6Zve055MYhNKwABFBOCBOk/KofB8+mGDqIxibukmuGesgb+bIN4sBytLP9W+4JAYZp56UE8j2q6lJ6FqI0E355Oirpzseu9iuA4czMRHS/q+LSbv8xTfNS8WmArYACjKWyobiJ0dFzHOZHkuRDr+6V5hh843vTyQh1UM9V110tGfFN/2wK3UZ8uSrSdqvxile+zYRzlo1zkpywYXcoo87Z0shjwrX9VWfvfPPbP9bztoKLBOt0nX16R0IdPjwEAIciL7c9Ws4yRG2L/EP9dlostXSHJ9Z0ZWNlht5vlfdmi3DI17stOzGL2gO5VSDaw
  template:
    metadata:
      name: minio-root
      namespace: minio
    type: Opaque
