apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: postgres-pv
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 10Gi